01-16 - 01-20

diff --git a/libquvi/patches/lua52.patch b/libquvi/patches/lua52.patch
--- a/libquvi/patches/lua52.patch
+++ b/libquvi/patches/lua52.patch
@@ -1,6 +1,97 @@
-diff -Nur orig/configure.ac mod/configure.ac
---- orig/configure.ac	2013-11-04 13:55:25.000000000 +0100
-+++ mod/configure.ac	2016-10-21 14:40:24.893206932 +0200
+diff -Naur orig/configure patched/configure
+--- orig/configure	2013-11-10 08:45:43.000000000 +0100
++++ patched/configure	2021-05-25 21:44:27.634761813 +0200
+@@ -14968,12 +14968,12 @@
+     pkg_cv_liblua_CFLAGS="$liblua_CFLAGS"
+  elif test -n "$PKG_CONFIG"; then
+     if test -n "$PKG_CONFIG" && \
+-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua51 >= 5.1\""; } >&5
+-  ($PKG_CONFIG --exists --print-errors "lua51 >= 5.1") 2>&5
++    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua52 >= 5.1\""; } >&5
++  ($PKG_CONFIG --exists --print-errors "lua52 >= 5.1") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+   test $ac_status = 0; }; then
+-  pkg_cv_liblua_CFLAGS=`$PKG_CONFIG --cflags "lua51 >= 5.1" 2>/dev/null`
++  pkg_cv_liblua_CFLAGS=`$PKG_CONFIG --cflags "lua52 >= 5.1" 2>/dev/null`
+ 		      test "x$?" != "x0" && pkg_failed=yes
+ else
+   pkg_failed=yes
+@@ -14985,12 +14985,12 @@
+     pkg_cv_liblua_LIBS="$liblua_LIBS"
+  elif test -n "$PKG_CONFIG"; then
+     if test -n "$PKG_CONFIG" && \
+-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua51 >= 5.1\""; } >&5
+-  ($PKG_CONFIG --exists --print-errors "lua51 >= 5.1") 2>&5
++    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua52 >= 5.1\""; } >&5
++  ($PKG_CONFIG --exists --print-errors "lua52 >= 5.1") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+   test $ac_status = 0; }; then
+-  pkg_cv_liblua_LIBS=`$PKG_CONFIG --libs "lua51 >= 5.1" 2>/dev/null`
++  pkg_cv_liblua_LIBS=`$PKG_CONFIG --libs "lua52 >= 5.1" 2>/dev/null`
+ 		      test "x$?" != "x0" && pkg_failed=yes
+ else
+   pkg_failed=yes
+@@ -15011,9 +15011,9 @@
+         _pkg_short_errors_supported=no
+ fi
+         if test $_pkg_short_errors_supported = yes; then
+-	        liblua_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "lua51 >= 5.1" 2>&1`
++	        liblua_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "lua52 >= 5.1" 2>&1`
+         else
+-	        liblua_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "lua51 >= 5.1" 2>&1`
++	        liblua_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "lua52 >= 5.1" 2>&1`
+         fi
+ 	# Put the nasty error message in config.log where it belongs
+ 	echo "$liblua_PKG_ERRORS" >&5
+@@ -15552,12 +15552,12 @@
+     pkg_cv_liblua_CFLAGS="$liblua_CFLAGS"
+  elif test -n "$PKG_CONFIG"; then
+     if test -n "$PKG_CONFIG" && \
+-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua51 >= 5.1\""; } >&5
+-  ($PKG_CONFIG --exists --print-errors "lua51 >= 5.1") 2>&5
++    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua52 >= 5.1\""; } >&5
++  ($PKG_CONFIG --exists --print-errors "lua52 >= 5.1") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+   test $ac_status = 0; }; then
+-  pkg_cv_liblua_CFLAGS=`$PKG_CONFIG --cflags "lua51 >= 5.1" 2>/dev/null`
++  pkg_cv_liblua_CFLAGS=`$PKG_CONFIG --cflags "lua52 >= 5.1" 2>/dev/null`
+ 		      test "x$?" != "x0" && pkg_failed=yes
+ else
+   pkg_failed=yes
+@@ -15569,12 +15569,12 @@
+     pkg_cv_liblua_LIBS="$liblua_LIBS"
+  elif test -n "$PKG_CONFIG"; then
+     if test -n "$PKG_CONFIG" && \
+-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua51 >= 5.1\""; } >&5
+-  ($PKG_CONFIG --exists --print-errors "lua51 >= 5.1") 2>&5
++    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua52 >= 5.1\""; } >&5
++  ($PKG_CONFIG --exists --print-errors "lua52 >= 5.1") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+   test $ac_status = 0; }; then
+-  pkg_cv_liblua_LIBS=`$PKG_CONFIG --libs "lua51 >= 5.1" 2>/dev/null`
++  pkg_cv_liblua_LIBS=`$PKG_CONFIG --libs "lua52 >= 5.1" 2>/dev/null`
+ 		      test "x$?" != "x0" && pkg_failed=yes
+ else
+   pkg_failed=yes
+@@ -15595,9 +15595,9 @@
+         _pkg_short_errors_supported=no
+ fi
+         if test $_pkg_short_errors_supported = yes; then
+-	        liblua_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "lua51 >= 5.1" 2>&1`
++	        liblua_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "lua52 >= 5.1" 2>&1`
+         else
+-	        liblua_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "lua51 >= 5.1" 2>&1`
++	        liblua_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "lua52 >= 5.1" 2>&1`
+         fi
+ 	# Put the nasty error message in config.log where it belongs
+ 	echo "$liblua_PKG_ERRORS" >&5
+diff -Naur orig/configure.ac patched/configure.ac
+--- orig/configure.ac	2021-05-25 21:43:28.622340824 +0200
++++ patched/configure.ac	2013-11-04 13:55:25.000000000 +0100
 @@ -83,7 +83,7 @@
  
  # Checks for libraries.
